# Generated by Django 4.2 on 2024-08-09 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_category_hashtag_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.category'),
        ),
        migrations.AddField(
            model_name='publication',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='hashtag',
            field=models.ManyToManyField(null=True, related_name='hashtags', to='info.hashtag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_activ',
            field=models.BooleanField(null=True),
        ),
    ]
