# Generated by Django 4.2 on 2024-08-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_publication_category_publication_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='publication',
            name='hashtags',
            field=models.ManyToManyField(null=True, to='info.hashtag'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='info.category'),
        ),
    ]
