# Generated by Django 4.2 on 2024-08-12 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_publication_hashtag_publication_hashtags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=111)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='info.publication')),
            ],
        ),
    ]
