# Generated by Django 4.2 on 2024-08-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_publicationcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_ky',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ky',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(max_length=111, null=True),
        ),
        migrations.AlterField(
            model_name='publicationcomment',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
